### ISSUE TITLE
Research definition of mode and how to derive mode

### ISSUE THREAD

**Issue by Harman-Sahota** [COSC499-CAPSTONE-GROUP/Team-GitHub-Exercise-1#1]
**Acceptance Criteria:**

- [ ] documentation contains a well-researched and detailed explanation of what the mode is.
- [ ] How can mode be derived programmatically?

**Validation Techniques:**

- [ ] Documentation contains a well-researched explanation of mode.

**Comment by AbdulazizAlmutlaq0** [comment]
the issue has been successfully resolved
