### ISSUE TITLE
Document what mode  is and how it works

### ISSUE THREAD

**Issue by Harman-Sahota** [COSC499-CAPSTONE-GROUP/Team-GitHub-Exercise-1#11]
**Acceptance Criteria:**

- [ ] documentation contains a  well-researched and detailed explanation of what the mode is.
- [ ] To be explained mathematically in the documentation -  how mode can be derived from a set of numbers.
- [ ] The documentation is formatted well. 
- [ ] An explanation of how this mathematical entity is derived through code.
- [ ] For ease of understanding an example of how mode can be found is provided.
- [ ]  The documentation should be completed by September 23, 2022, at 11 PM PST for final submission.

**Validation techniques:**

- [ ] Readme file is updated with how a user can use this feature on their own machine and is verified by another member before merging the PR.

**Comment by AbdulazizAlmutlaq0** [comment]
issue resolved
