### ISSUE TITLE
Refractor code for mode function to be more organized 

### ISSUE THREAD

**Issue by Harman-Sahota** [COSC499-CAPSTONE-GROUP/Team-GitHub-Exercise-1#12]
**Acceptance Criteria:**

- [ ] The code is indented properly so that it is easy to differentiate between blocks/classes/methods.
- [ ] The code should be completed by September 23, 2022, at 3 PM PST for peer review.

**Validation techniques:**

- [ ] A team member views the code and is able to differentiate parts of code (class definitions/methods/blocks of code) at one glance.

**Comment by AbdulazizAlmutlaq0** [comment]
issues resolved
