### ISSUE TITLE
Add Comments to the code for finding the mode in an array of integers

### ISSUE THREAD

**Issue by Harman-Sahota** [COSC499-CAPSTONE-GROUP/Team-GitHub-Exercise-1#24]
**Acceptance Criteria:**

- [ ] Comments should clearly explain what each part of the code is doing.
- [ ] The code comments should be completed by September 23, 2022, at 3 PM PST for peer review.
- [ ] Comments are precise and up to a point and can make understanding the code more accessible, such that even a non-programmer can make out what a part of the code is doing.

**Validation techniques:**

- [ ] A team member goes through the code and sees if the comments are written in a simple, easy-to-understand language and that they can understand what every part of the code is doing.

**Comment by AbdulazizAlmutlaq0** [comment]
Issues resolved
