### ISSUE TITLE
Code the most efficient algorithm to find mode in an array

### ISSUE THREAD

**Issue by Harman-Sahota** [COSC499-CAPSTONE-GROUP/Team-GitHub-Exercise-1#4]
**Acceptance Criteria:**

- [ ] It is explained in the documentation as to why the used algorithm was chosen and why it was better than other possible choices.
- [ ] The program executes the results almost instantly (maximum time execution is one second).
- [ ] The code displays the correct output to the user.
- [ ] There are no bugs in the code.
- [ ] The code should be completed by September 23, 2022, at 3 PM PST for peer review.

**Validation Techniques:**

- [ ] JUnit tests are passed.
- [ ] There are no bugs in the code.
- [ ] The code has the best time complexity and/or space complexity.

**Comment by AbdulazizAlmutlaq0** [comment]
issue has been resolved
