### ISSUE TITLE
Test the method to ensure there are no issues for mode 

### ISSUE THREAD

**Issue by Harman-Sahota** [COSC499-CAPSTONE-GROUP/Team-GitHub-Exercise-1#7]
**Acceptance Criteria:**

- [ ] JUnit tests are written to test the method.
- [ ] The tests cover all sorts of inputs a user can give and has variety.
- [ ] The program executes the results almost instantly (maximum time execution is one second).
- [ ] The testing should be completed by September 23, 2022, at 3 PM PST.

**Validation Techniques:**

- [ ] The Method passes all JUnit tests and there are no bugs in the code.

**Comment by AbdulazizAlmutlaq0** [comment]
issue resolved
