### ISSUE TITLE
Research definition of mean and how to derive the mean

### ISSUE THREAD

**Issue by AbdulazizAlmutlaq0** [COSC499-CAPSTONE-GROUP/Team-GitHub-Exercise-1#9]
Acceptance Criteria:
- [ ]  The documentation delivers a well established explanation of what the mean is.
- [ ] How can the mean be attained (programmatically)

Validation technique:
- [ ] The documentation needs to include a well established explanation of mean.

**Comment by Harman-Sahota** [comment]
issue has been resolved
